apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: srv
    demo: kth
    year: "2022"
  name: srv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: srv
  strategy: 
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: srv
    spec:
      containers:
      - image: gcr.io/kth-demo-22/kth-demo-22
        name: kth-demo-22
        ports:
        - containerPort: 8080
        resources: 
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName